[service]
Name="godemo"
displayname="go语言的demo"
version="v1.0"
host="10.1.1.51"
port=9527

[Consul]
Host="test.dc.rpdns.com"
Port=8500

[Mysql]
Host="test.db.rpdns.com"
Port=3306
User="root"
Pwd="Rp000000"
Default="test"

[Cache]
Host="test.db.rpdns.com"
Port=6979
Pwd="qlwhIPO82@#KDFQAwe"
Default=0

[Rsa]
PublicKey="rsa_1024_pub.pem"
PrivateKey="rsa_1024_priv.pem"
Issuer="rp-pet.com"